apiVersion: v1
kind: PersistentVolume
metadata:
  name: simod-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/simod-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
                - kind-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simod-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: simod-volume
  resources:
    requests:
      storage: 2Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager-role
  namespace: default
rules:
  - apiGroups: [ "", "batch" ]
    resources: [ "jobs" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simod-http
spec:
  selector:
    matchLabels:
      app: simod-http
  template:
    metadata:
      labels:
        app: simod-http
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: simod-http
          image: nokal/simod-http:0.3.1
          env:
            - name: BROKER_URL
              value: "amqp://guest:guest@rabbitmq-service:5672"
            - name: SIMOD_EXCHANGE_NAME
              value: "simod"
            - name: SIMOD_PENDING_ROUTING_KEY
              value: "requests.status.pending"
            - name: SIMOD_HTTP_PORT
              value: "8000"
            - name: SIMOD_HTTP_STORAGE_PATH
              value: "/tmp/simod-volume/data"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simod-job-controller
spec:
  selector:
    matchLabels:
      app: simod-job-controller
  template:
    metadata:
      labels:
        app: simod-job-controller
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: simod-job-controller
          image: nokal/simod-job-controller:0.3.1
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: SIMOD_EXCHANGE_NAME
              value: simod
            - name: SIMOD_PENDING_ROUTING_KEY
              value: requests.status.pending
            - name: SIMOD_DOCKER_IMAGE
              value: nokal/simod:3.3.0
            - name: KUBERNETES_NAMESPACE
              value: default
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simod-request-status-observer
spec:
  selector:
    matchLabels:
      app: simod-request-status-observer
  template:
    metadata:
      labels:
        app: simod-request-status-observer
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: simod-request-status-observer
          image: nokal/simod-request-status-observer:0.1.2
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: SIMOD_EXCHANGE_NAME
              value: simod
            - name: SIMOD_STATUS_WORKER_BINDING_KEY
              value: requests.status.*
            - name: SIMOD_HTTP_STORAGE_PATH
              value: /tmp/simod-volume/data
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume