{
 "title": "Simod",
 "time": { "from": "2023-03-07T16:30:02.914Z", "to": "2023-03-07T16:41:41.032Z" },
 "panels": [
  {
   "title": "Jobs Pending",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Pending Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Running Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of jobs by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}