{
 "title": "Simod",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Simod Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs Pending",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Waiting Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Processing Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kube Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Jobs Succeeded (kube)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "sum(kube_job_status_succeeded)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of Active Jobs (kube)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "sum(kube_job_status_active)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs Failed (kube)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sum(kube_job_status_failed)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Container Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Simod Container Memory Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{image=\"docker.io/nokal/simod:3.3.0\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU User Seconds Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "avg(container_cpu_user_seconds_total{image=\"docker.io/nokal/simod:3.3.0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}