{
 "title": "Simod",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jobs Pending",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge{status=\"succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Waiting Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Processing Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(simod_jobs_duration_seconds_sum{status=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(simod_jobs_gauge) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simod Container Memory Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{image=\"docker.io/nokal/simod:3.3.0\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container CPU User Seconds Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg(container_cpu_user_seconds_total{image=\"docker.io/nokal/simod:3.3.0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}