apiVersion: batch/v1
kind: Job
metadata:
  name: locust-master
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: locust-master
          image: nokal/simod-load-testing:0.2.1
          env:
            - name: SIMOD_HTTP_URL
              value: http://simod-http:8000
            - name: LOCUST_HOST
              value: http://simod-http:8000
            - name: LOCUST_USERS
              value: "100"
            - name: LOCUST_SPAWN_RATE
              value: "1"
            - name: LOCUST_RUN_TIME
              value: "30s"
            - name: LOCUST_HEADLESS
              value: "true"
            - name: LOCUST_EXPECT_WORKERS
              value: "1"
            - name: LOCUST_MODE_MASTER
              value: "true"
            - name: LOCUST_FILE
              value: "PrepaidTravelCostSingleTask.py"
            - name: REPORT_OUTPUT_DIR
              value: /tmp/simod-volume/locust
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: locust-worker
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: locust-worker
          image: nokal/simod-load-testing:0.2.1
          env:
            - name: SIMOD_HTTP_URL
              value: http://simod-http:8000
            - name: LOCUST_MODE_WORKER
              value: "true"
            - name: LOCUST_MASTER_NODE_HOST
              value: locust-master
            - name: LOCUST_FILE
              value: "PrepaidTravelCostSingleTask.py"              
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  ports:
    - name: web
      port: 8089
    - name: slave
      port: 5557
  selector:
    app: locust-master