apiVersion: apps/v1
kind: Deployment
metadata:
  name: simod-http
spec:
  selector:
    matchLabels:
      app: simod-http
  template:
    metadata:
      labels:
        app: simod-http
    spec:
      volumes:
        - name: simod-data
          persistentVolumeClaim:
            claimName: simod-volume-claim
      containers:
        - name: simod-http
          image: nokal/simod-http:0.11.1
          command: [ "/bin/bash" ]
          args: [ "run_uvicorn.sh" ]
          env:
            - name: BROKER_URL
              value: "amqp://guest:guest@rabbitmq-service:5672"
            - name: SIMOD_EXCHANGE_NAME
              value: "simod"
            - name: SIMOD_PENDING_ROUTING_KEY
              value: "requests.status.pending"
            - name: SIMOD_HTTP_HOST
              value: "0.0.0.0"
            - name: SIMOD_HTTP_PORT
              value: "8000"
            - name: SIMOD_HTTP_STORAGE_PATH
              value: "/tmp/simod-volume/data"
            - name: SIMOD_HTTP_LOG_LEVEL
              value: "info"
            - name: SIMOD_GUNICORN_WORKERS
              value: "4"
            - name: MONGO_URL
              value: "mongodb://mongodb:27017"
            - name: MONGO_DATABASE
              value: "simod"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              value: "example"
            - name: MONGO_REQUESTS_COLLECTION
              value: "requests"
          resources:
            requests:
              cpu: 256m
              memory: 256Mi
          volumeMounts:
            - name: simod-data
              mountPath: /tmp/simod-volume
---
apiVersion: v1
kind: Service
metadata:
  name: simod-http
  labels:
    app: simod-http
spec:
  selector:
    app: simod-http
  ports:
    - name: web
      port: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simod-http
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simod-http
