- name: Set up Pod network
  hosts: pix-control-plane
  become: yes
  tasks:
    - name: Set iptables to see the bridged traffic
      shell: |
        cat <<EOF | tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

        modprobe overlay
        modprobe br_netfilter

        cat <<EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF

        sysctl --system

    - name: Create the .conf file to load the modules at bootup
      shell: |
        cat <<EOF | tee /etc/modules-load.d/crio.conf
        overlay
        br_netfilter
        EOF

        cat <<EOF | /etc/sysctl.d/99-kubernetes-cri.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF

        modprobe overlay
        modprobe br_netfilter

        sysctl --system

    - name: Add the CRI-O repository
      vars:
        os: "xUbuntu_20.04" # cri-o for Ubuntu 20.04 is compatible with Ubuntu 22
        version: "1.23"
      shell: |
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/ /" | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ version }}/{{ os }}/ /" | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ version }}.list
        curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ version }}/{{ os }}/Release.key | apt-key add -
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/Release.key | apt-key add -
    
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install CRI-O
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - cri-o
        - cri-o-runc
        - cri-tools

    - name: Reload systemd
      shell: systemctl daemon-reload

    - name: Enable CRI-O
      shell: systemctl enable crio --now
