services:
  rabbitmq-service:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  simod-http:
    image: nokal/simod-http:0.3.1
    depends_on:
      - rabbitmq-service
    restart: unless-stopped
    environment:
      BROKER_URL: amqp://guest:guest@rabbitmq-service:5672
      SIMOD_EXCHANGE_NAME: simod
      SIMOD_PENDING_ROUTING_KEY: requests.status.pending
      SIMOD_HTTP_PORT: 8000
      SIMOD_HTTP_STORAGE_PATH: /tmp/simod-volume/data
    volumes:
      - /tmp/simod-volume/:/tmp/simod-volume/
    ports:
      - 8000:8000

  simod-job-controller:
    image: nokal/simod-job-controller:0.3.0
    depends_on:
      - rabbitmq-service
    restart: unless-stopped
    environment:
      BROKER_URL: amqp://guest:guest@rabbitmq-service:5672
      SIMOD_EXCHANGE_NAME: simod
      SIMOD_PENDING_ROUTING_KEY: requests.status.pending
      SIMOD_DOCKER_IMAGE: nokal/simod:3.3.0
      KUBERNETES_NAMESPACE: default

  simod-request-status-observer:
    image: nokal/simod-request-status-observer:0.1.1
    depends_on:
      - rabbitmq-service
    restart: unless-stopped
    environment:
      BROKER_URL: amqp://guest:guest@rabbitmq-service:5672
      SIMOD_EXCHANGE_NAME: simod
      SIMOD_STATUS_WORKER_BINDING_KEY: requests.status.*
      SIMOD_HTTP_STORAGE_PATH: /tmp/simod-volume/data
    volumes:
      - /tmp/simod-volume/:/tmp/simod-volume/


